language: node_js
node_js:
- '8'
before_deploy:
- openssl aes-256-cbc -K $encrypted_e5ce453b448a_key -iv $encrypted_e5ce453b448a_iv
  -in vamos-fazer-compras-40da0e7eab52.json.enc -out vamos-fazer-compras-40da0e7eab52.json
  -d
deploy:
  provider: gae
  keyfile: vamos-fazer-compras-40da0e7eab52.json
  project: vamos-fazer-compras
